### ISSUE TITLE
ERREUR:  la colonne vm_observations_mailles.annee n'existe pas

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature-atlas#261]
Le code SQL pour la VM `atlas.vm_observations_mailles` est différent dans les scripts  `data/update_vm_observations.sql` et `data/observations_mailles.sql`.
Le champ `annee` n'est pas créé dans le code du script `data/update_vm_observations.sql`.

Du coup, si on suit la doc est que l'on exécute le script `data/update_vm_observations.sql` après avoir exécuter `./install_db.sh` l'erreur suivante est générée:
```
Traceback (most recent call last):
  File "/home/jpm/workspace/geonature/web/geonature_atlas/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/jpm/workspace/geonature/web/geonature_atlas/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: ERREUR:  la colonne vm_observations_mailles.annee n'existe pas
LINE 1: ...servations_mailles.id_observation) AS nb_obs, max(atlas.vm_o...
```

**Comment by camillemonchicourt** [comment]
Oui on a créé le script update_vm_observations.sql tout en sachant qu'il y avait un risque à ne pas le maintenir correctement, en parallèle du script d'installation.
Selon moi il faut supprimer ce script.
